export const DEFAULT_APPS: AppRegistry[] = [
  {
    app_key: "records",
    title_zh: "记账系统",
    title_en: "Accounting",
    title_ms: "Sistem Akaun",
    icon: "/app-icons/records.png",
    app_path: "/dashboard/records",
    sort_order: 10,
    enabled: true,
    is_active: true,
  },
  {
    app_key: "customers",
    title_zh: "客户管理",
    title_en: "Customers",
    title_ms: "Pelanggan",
    icon: "/app-icons/customers.png",
    app_path: "/dashboard/customers",
    sort_order: 20,
    enabled: true,
    is_active: true,
  },
  {
    app_key: "products",
    title_zh: "产品管理",
    title_en: "Products",
    title_ms: "Produk",
    icon: "/app-icons/products.png",
    app_path: "/dashboard/products",
    sort_order: 30,
    enabled: true,
    is_active: true,
  },
  {
    app_key: "invoices",
    title_zh: "发票系统",
    title_en: "Invoices",
    title_ms: "Invois",
    icon: "/app-icons/invoices.png",
    app_path: "/dashboard/invoices",
    sort_order: 40,
    enabled: true,
    is_active: true,
  },
  {
    app_key: "extensions",
    title_zh: "扩展功能",
    title_en: "Extensions",
    title_ms: "Fungsi Tambahan",
    icon: "/app-icons/extensions.png",
    app_path: "/dashboard/extensions",
    sort_order: 50,
    enabled: true,
    is_active: true,
  },
  {
    app_key: "nkshop",
    title_zh: "NK网店",
    title_en: "NK Shop",
    title_ms: "NK Kedai",
    icon: "/app-icons/nkshop.png",
    app_path: "/dashboard/nkshop",
    sort_order: 60,
    enabled: true,
    is_active: true,
  },
];
